using RoR2EditorKit.CodeGen;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Moonstorm.Editor.CodeGen
{
    internal class CodeGenUtil
    {
        public static void WriteHeader(Writer writer, string toolName, string toolVersion)
        {
            writer.WriteLine(
                "//------------------------------------------------------------------------------\n"
                + "// <auto-generated>\n"
                + $"//     This code was auto-generated by com.TeamMoonstorm.MoonstormSharedUtils:{toolName}\n"
                + $"//     version {toolVersion}\n"
                + "//\n"
                + "//     Feel free to remove this commment block.\n"
                + "// </auto-generated>\n"
                + "//------------------------------------------------------------------------------\n");
        }
    }
}
